set -g mouse on

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix to Ctrl+Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Start windows and panes indexing from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Make copying vim-like
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Return last saved session when starting tmux
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Theme
grey_light="#D8DEE9"
grey="#ABB2BF"
dark_grey="#3B4252"
green_soft="#A3BE8C"
green_muted="#81C181"
cyan="#00FFFF"
cyan_soft="#88C0D0"
blue_muted="#81A1C1"

set -g status-left-length 100
set -g status-style "fg=${grey_light},bg=default"
set -g status-left "#[fg=${green_soft},bg=default,bold]#{?client_prefix,,"#S"}#[fg=#000000,bg=${green_muted},bold]#{?client_prefix,"#S",}#[fg=${grey_light},bg=default,nobold] | "
set -g status-right "#[bg=#808080,fg=#000000,bold] %m/%d #[bg=#D3D3D3] %H:%M:%S "
set -g window-status-current-format "#[bold]#I:#W#[fg=${cyan}]*"
set -g window-status-format "#[fg=${grey}]#I:#W"
set -g mode-style "fg=${dark_grey},bg=${blue_muted}"
set -g pane-border-style "fg=${dark_grey}"
set -g pane-active-border-style "fg=${grey}"

run '~/.tmux/plugins/tpm/tpm'
