vim.loader.enable(true)
vim.g.mapleader = " "
vim.keymap.set("n", "<leader>rs", ":so ~/.config/nvim/init.lua | restart<cr>")
require("options")
require("colorscheme")
require("keymaps")
require("lsp")
require("autocmd")
require("netrw")
require("find")
require("ripgrep")
require("term")
require("pack")
require("plugins.all")
